# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\ProSegCode\src\main\UI\MainWindow.ui'
#
# Created: Wed Nov 02 15:35:05 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(976, 670)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imgView = QtGui.QGraphicsView(self.centralwidget)
        self.imgView.setGeometry(QtCore.QRect(180, 330, 281, 261))
        self.imgView.setObjectName(_fromUtf8("imgView"))
        self.groundImgVeiw = QtGui.QGraphicsView(self.centralwidget)
        self.groundImgVeiw.setGeometry(QtCore.QRect(340, 20, 281, 261))
        self.groundImgVeiw.setObjectName(_fromUtf8("groundImgVeiw"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 290, 111, 29))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 290, 91, 29))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 610, 31, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.segView = QtGui.QGraphicsView(self.centralwidget)
        self.segView.setGeometry(QtCore.QRect(20, 20, 281, 261))
        self.segView.setObjectName(_fromUtf8("segView"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 270, 131, 211))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.SegmentButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.SegmentButton.setObjectName(_fromUtf8("SegmentButton"))
        self.verticalLayout.addWidget(self.SegmentButton)
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.TrainingButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.TrainingButton.setObjectName(_fromUtf8("TrainingButton"))
        self.verticalLayout.addWidget(self.TrainingButton)
        spacerItem1 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.LoadTrainDataButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.LoadTrainDataButton.setObjectName(_fromUtf8("LoadTrainDataButton"))
        self.verticalLayout.addWidget(self.LoadTrainDataButton)
        spacerItem2 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.ExitButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.ExitButton.setObjectName(_fromUtf8("ExitButton"))
        self.verticalLayout.addWidget(self.ExitButton)
        self.OpenImge = QtGui.QPushButton(self.centralwidget)
        self.OpenImge.setGeometry(QtCore.QRect(500, 380, 121, 31))
        self.OpenImge.setObjectName(_fromUtf8("OpenImge"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(660, 30, 171, 171))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Slicelabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Slicelabel.setObjectName(_fromUtf8("Slicelabel"))
        self.horizontalLayout_2.addWidget(self.Slicelabel)
        self.SliceSlider = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.SliceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SliceSlider.setObjectName(_fromUtf8("SliceSlider"))
        self.horizontalLayout_2.addWidget(self.SliceSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Iterlabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Iterlabel.setObjectName(_fromUtf8("Iterlabel"))
        self.horizontalLayout_3.addWidget(self.Iterlabel)
        self.IterSlider = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.IterSlider.setOrientation(QtCore.Qt.Horizontal)
        self.IterSlider.setObjectName(_fromUtf8("IterSlider"))
        self.horizontalLayout_3.addWidget(self.IterSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Treelabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Treelabel.setObjectName(_fromUtf8("Treelabel"))
        self.horizontalLayout_4.addWidget(self.Treelabel)
        self.TreeSlider = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.TreeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TreeSlider.setObjectName(_fromUtf8("TreeSlider"))
        self.horizontalLayout_4.addWidget(self.TreeSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.depthSlider = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.depthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.depthSlider.setObjectName(_fromUtf8("depthSlider"))
        self.horizontalLayout_5.addWidget(self.depthSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.BootstrapButton = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.BootstrapButton.setObjectName(_fromUtf8("BootstrapButton"))
        self.verticalLayout_3.addWidget(self.BootstrapButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLoad = QtGui.QMenu(self.menubar)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen_GroundImg = QtGui.QAction(MainWindow)
        self.actionOpen_GroundImg.setObjectName(_fromUtf8("actionOpen_GroundImg"))
        self.actionSave_Model = QtGui.QAction(MainWindow)
        self.actionSave_Model.setObjectName(_fromUtf8("actionSave_Model"))
        self.actionLoad_model = QtGui.QAction(MainWindow)
        self.actionLoad_model.setObjectName(_fromUtf8("actionLoad_model"))
        self.actionLoad_GroundImg = QtGui.QAction(MainWindow)
        self.actionLoad_GroundImg.setObjectName(_fromUtf8("actionLoad_GroundImg"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuLoad.addAction(self.actionLoad_model)
        self.menuLoad.addAction(self.actionLoad_GroundImg)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLoad.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ExitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "前列腺分割平台", None))
        self.label_2.setText(_translate("MainWindow", "Ground Truth Image", None))
        self.label.setText(_translate("MainWindow", "Segment Image", None))
        self.label_3.setText(_translate("MainWindow", "Image", None))
        self.SegmentButton.setText(_translate("MainWindow", "Segment", None))
        self.TrainingButton.setText(_translate("MainWindow", "Training", None))
        self.LoadTrainDataButton.setText(_translate("MainWindow", "Load Training Data", None))
        self.ExitButton.setText(_translate("MainWindow", "Exit", None))
        self.OpenImge.setText(_translate("MainWindow", "OpenImge", None))
        self.Slicelabel.setText(_translate("MainWindow", "Slice:   ", None))
        self.Iterlabel.setText(_translate("MainWindow", "Iter:    ", None))
        self.Treelabel.setText(_translate("MainWindow", "TreeNum: ", None))
        self.label_4.setText(_translate("MainWindow", "MaxDepth:", None))
        self.BootstrapButton.setText(_translate("MainWindow", "Bootstrap", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuLoad.setTitle(_translate("MainWindow", "Load", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionOpen_GroundImg.setText(_translate("MainWindow", "Open GroundImg", None))
        self.actionSave_Model.setText(_translate("MainWindow", "Save Model", None))
        self.actionLoad_model.setText(_translate("MainWindow", "Load Model", None))
        self.actionLoad_GroundImg.setText(_translate("MainWindow", "Load GroundImg", None))

